import type { Metadata } from "next";
import { localeCodes } from "@/i18n/config";

const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL || "https://unfold.app";

export function generateLandingMetadata(locale: string): Metadata {
  const titles: Record<string, string> = {
    en: "Unfold — Personal Timing App | Daily Momentum for Love, Health & Work",
    fr: "Unfold — App de timing personnel | Momentum quotidien Amour, Santé & Travail",
    es: "Unfold — App de timing personal | Momentum diario para Amor, Salud & Trabajo",
  };

  const descriptions: Record<string, string> = {
    en: "Know when life moves in your favor. Unfold gives you a free daily momentum score across Love, Health, and Work. See your peaks, compare rhythms, and plan smarter. Download the app.",
    fr: "Sachez quand la vie joue en votre faveur. Unfold vous offre un score de momentum quotidien gratuit en Amour, Santé et Travail. Voyez vos pics, comparez vos rythmes. Téléchargez l'app.",
    es: "Descubre cuándo la vida se mueve a tu favor. Unfold te da un score de impulso diario gratuito en Amor, Salud y Trabajo. Ve tus picos, compara ritmos. Descarga la app.",
  };

  const title = titles[locale] ?? titles.en;
  const description = descriptions[locale] ?? descriptions.en;
  const url = `${BASE_URL}/${locale}`;

  // Build hreflang alternates
  const languages: Record<string, string> = {};
  for (const code of localeCodes) {
    languages[code] = `${BASE_URL}/${code}`;
  }
  languages["x-default"] = `${BASE_URL}/en`;

  return {
    title,
    description,
    alternates: {
      canonical: url,
      languages,
    },
    openGraph: {
      title,
      description,
      type: "website",
      siteName: "Unfold",
      url,
      locale: locale === "fr" ? "fr_FR" : locale === "es" ? "es_ES" : "en_US",
      // OG image is auto-generated by app/[locale]/opengraph-image.tsx
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      // Twitter image is auto-generated by app/[locale]/opengraph-image.tsx
    },
    applicationName: "Unfold",
    category: "lifestyle",
    keywords: [
      "personal timing app",
      "daily momentum",
      "love health work",
      "compatibility",
      "personal rhythm",
      "daily clarity",
    ],
  };
}
